[book]

title = "Vulkan 教程 (Rust)"
authors = ["Kyle Mayes", "Chuigda WhiteGive (翻译者)"]

description = "Vulkan Tutorial (Rust) 的中文翻译"

language = "zh"
multilingual = false

src = "src"

edition = "edition2018"

[output.html]

git-repository-url = "https://github.com/KyleMayes/vulkanalia"

[preprocessor.vk]

command = "vk-preprocessor"
renderer = ["html"]
